name: test

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Testing
        run: |
          pytest tests
          



